### PR TITLE
Fix Windows path handling in view load autocommand

### LINKED ISSUE #46: vim-stay error E867: (NFA) Unknown operator '\zh'
Hi Developer,
When I use this plugin in Windows, I tend to get this error when opening files.

I tried to debug it, and comment out the `catch "other errors` block of `stay#view#load(winid)`, I get the following verbose output of vim:

```
E867: (NFA) Unknown operator '\zh'
E68: Invalid character after \z
No matching autocommands

Error detected while processing function <SNR>9_LoadView[8]..stay#view#load:
line   31:
E867: (NFA) Unknown operator '\zh'
E68: Invalid character after \z
```

The "zh" string is the starting of my username, so I think it's caused by the un-escape window path.
Would you please give it a fix ?

Thanks

### PR DESCRIPTION
**Pull request by kopischke**
This is embarrassing: the designated logic for handling Windows `viewdir` paths with backslashes was faulty _and_ saddled with a buggy implementation. This has probably only gone unnoticed for such a long time through a confluence of Vim defaults and Windows user usage patterns. Closes #46.

### CODE REVIEW

**Comment by zhimsel** [comment]
@skt041959 would you be able to test this branch on your Windows setup? I'll do some independent testing on my side (MacOS/Linux) as well.

**Comment by kopischke** [comment]
@zhimsel when you test this on a Mac / \*nix system please make sure to check what happens when you set `viewdir` to a path with spaces, which IIRC needs to be escaped with a backlash. If my suspicion is correct and if the backslash is returned when querying the setting, line 75 may introduce a spurious slash into the path. This is not exactly a regression (the old version would do that too), but the patch expands the scope of the substitution and hence the possible error surface …

**Comment by zhimsel** [comment]
Will do.

----

For the room: I should be able to have time to test this late this weekend or early next week. I'm traveling on business and I've got a tight schedule until then.

**Comment by kopischke** [comment]
> @zhimsel when you test this on a Mac / *nix system please make sure to check what happens when you set `viewdir` to a path with spaces, which IIRC needs to be escaped with a backlash. If my suspicion is correct and if the backslash is returned when querying the setting, line 75 may introduce a spurious slash into the path. This is not exactly a regression (the old version would do that too), but the patch expands the scope of the substitution and hence the possible error surface …

I’ve read up a bit on `option-backslash`, and to my understanding the escaping happens at the setting stage, which means `:set?` should return the final string. That leaves us in the clear as to backslash using systems, as the path separator is never a legal path name character, but it strikes me the backlash very much is a legal path name character on \*nix systems. The final patch thus would have to look more like this:

```vim
let l:slash = exists('+shellslash') ? '\\' : '/'
let s:viewdir.path = substitute(s:viewdir.option, '\v'.l:slash.'+', '/', 'g')
```

**Comment by kopischke** [comment]
@zhimsel @skt041959 I’ve pushed a new commit to this PR that should cover all eventualities on both Windows and \*nix systems (that `SourcePre` thing really was embarrassingly broken). To test, you will need to:

1. set `g:stay_verbosity` to 1;
2. define a `SessionLoadPost` autocommand you can watch;
3. open a file that has a known view state with the default `viewdir`;
4. make sure the view state has loaded;
5. make sure the `SessionLoadPost` event fired;
6. make sure no errors occurred;
7. set `viewdir` to a path with spaces;
7. repeat 3. to 6. above.

It’s probably better to test this both in Vim and Neovim, as it seems these two handle a lot of things differently by now … Sorry for misusing you as testers / debuggers, but this is the best I can do.

If this works, I would squash and force push this PR so that it is ready to merge.

**Comment by zhimsel** [comment]
@kopischke testing this on MacOS, I'm encountering an issue around https://github.com/zhimsel/vim-stay/blob/8a59ac6fbe8ecc5ba85be2867171b94ee57e0a57/autoload/stay/view.vim#L79

I set `au SessionLoadPost * echom "SessionLoadPost happened"` in a minimal vimrc with just vim-stay and `let g:stay_verbosity=1` to test this.

This works fine with vim 8.1, but when using nvim 0.3.4, the `l:path` variable is unset (and thus produces an error). However, neither program is firing a `SessionLoadPost` event.

As far as I'm aware, the `path` variable (both global and local variants) is the vim equivalent of the `$PATH` shell env var. This appears to be the case in both vim and nvim. Were you intending on using that variable, or trying to set your own?

**Comment by kopischke** [comment]
> Were you intending on using that variable, or trying to set your own?

Ugh, neither nor, that is a remnant of a previous iteration of the patch … I’ll push a fixup.

**Comment by kopischke** [comment]
I force pushed an update. Care to give it another whirl?

**Comment by zhimsel** [comment]
@skt041959 Sorry for the super-delayed response on this.

@kopischke I tested your revised commit. Works well on my end. I'm going to merge this. Looks like @skt041959 hasn't gotten a chance to test this as well, but we can always fix anything that pops up later.

Thanks again for pushing this fix!

**Pull request merged**
