### PR TITLE
Only echo errors originating from the plug-in

### PR DESCRIPTION
**Pull request by kopischke**
Previously, vim-stay could be lead to echo `v:errmsg` when it is irrelevant to the plug-in by setting `g:stay_verbosity` > 1. This also unifies error handling across the whole `plugin/stay` file, improving
maintainability.

\[Yeah, my refreshing of memory about _vim-stay’s_ workings has led me onto unexpected paths 🤗 …\].

### CODE REVIEW

**Comment by zhimsel** [comment]
@kopischke thanks for this! I'll check this branch out locally and work with it for a few days to see if any issues pop up. Will merge soon.

**Comment by zhimsel** [comment]
This... is really strange. When running vim with this branch (and either my vimrc or a blank `vim-stay`-only vimrc), whenever I open `plugin/stay.vim`, the buffer is overwritten with a few minor changes and I get the following error:

```
Error detected while processing function <SNR>60_LoadView:
line    9:
E486: Pattern not found: HandleErrMsg(l
```

<details><summary>This patch is the result (click to expand)</summary>

```diff
diff --git a/plugin/stay.vim b/plugin/stay.vim
index f816dd1..38d130a 100644
--- a/plugin/stay.vim
+++ b/plugin/stay.vim
@@ -29,7 +29,7 @@ let s:integrations = [] " }}}
 " PLUG-IN MACHINERY {{{
 " Echo v:errmsg depending on the set verbosity level,
 " making sure we do not echo messages that are not vim-stay errors:
-function! s:HandleErrMsg(level) abort
+unction! s:done)evel) abort
   if a:level < min([1, g:stay_verbosity])
     echomsg v:errmsg
   endif
@@ -52,7 +52,7 @@ function! s:MakeView(stage, bufnr, winid) abort
   endif

   let l:done = stay#view#make(a:winid)
-  s:HandleErrMsg(l:done)
+  s:done):done)
   if l:done is  1
     let l:state.left = extend(l:left, {string(a:stage): localtime()})
   endif
@@ -69,7 +69,7 @@ function! s:LoadView(bufnr, winid) abort
   endif

   let l:done = stay#view#load(a:winid)
-  s:HandleErrMsg(l:done)
+  s:done):done)
   return l:done
 endfunction
```
</details>
<br>
It's baffling me. It happens with `g:stay_verbosity` set to either `0` or `1`, or unset at all. It doesn't happen when opening any other file I've tried (in or outside of `vim-stay`).

---

UPDATE: This also happens when doing the following:
- open a vim session with vim-stay loaded on this branch
- `:e test.txt` and `:w`
- Type out `HandleErrMsg(l:test)`
- Upon `:w`, the text will be replaced with `done):test)`

I'm guessing there's some logic here that I'm not seeing that's inadvertently doing some text replacement in the buffer.

**Comment by kopischke** [comment]
~~I would guess that the malfunction is somehow due to the nested script scope (calling an `s:` function from another while inside an autocommand event). Why Vim then decides to overwrite stuff is beyond me … will fix.~~ EDIT: much. more. stupid. error. See comment below.

**Comment by kopischke** [comment]
TFW you (i.e.: me) forgot about the Vim script `:call` command …

Head meets desk. Repeatedly.

I force pushed a fix that should actually work.

**Comment by zhimsel** [comment]
> TFW you (i.e.: me) forgot about the Vim script `:call` command …

D'oh! I tested the revised branch locally, and it all looks cromulent to me.

**Pull request merged**
